---

- name: Install epel-release on Amazon Linux
  when: ansible_facts['distribution'] == 'Amazon'
  shell:
    creates: /etc/yum.repos.d/epel.repo
    cmd: amazon-linux-extras install -y epel

- name: Install epel-release on non-Amazon Linux
  when: ansible_facts['distribution'] != 'Amazon'
  yum:
    state: present
    name:
      - epel-release
