# ========
# Install and configure Python packages for SOCA
# Maintainer: mcrozes@
# ========

- name: Expected Python URL
  debug:
    msg: "{{ PYTHON_URL }}"

- name: Expected Python Checksum hash (md5)
  debug:
    msg: "{{ PYTHON_HASH }}"

- name: Download Python installer
  get_url:
    url: "{{ PYTHON_URL }}"
    dest: /root/
    checksum: "md5:{{ PYTHON_HASH }}"

- name: Extract Python installer
  unarchive:
    src: "/root/{{ PYTHON_TGZ }}"
    dest: "/root/"

- name: Build Python
  shell: |
    ./configure LDFLAGS="-L/usr/lib64/openssl" CPPFLAGS="-I/usr/include/openssl" --prefix=/apps/soca/{{ SOCA_CLUSTER_ID | quote }}/python/{{ PYTHON_VERSION | quote }}
    make
    make install
  args:
    executable: /bin/bash
    chdir: "/root/Python-{{ PYTHON_VERSION }}/"

- name: Create symbolic link for Python
  file:
    src: "/apps/soca/{{ SOCA_CLUSTER_ID }}/python/{{ PYTHON_VERSION }}"
    dest: "/apps/soca/{{ SOCA_CLUSTER_ID }}/python/latest"
    state: link

- name: Install PIP requirements.txt
  pip:
    name:
      - asn1crypto==1.3.0
      - awscli==1.16.151
      - boto3==1.9.141
      - botocore==1.12.141
      - cffi==1.14.0
      - cfn-flip==1.2.2
      - Click==7.0
      - colorama==0.3.9
      - cryptography==2.6.1
      - docutils==0.16
      - ecdsa==0.15
      - elasticsearch==6.3.1
      - Flask==1.0.3
      - Flask-WTF==0.14.3
      - gunicorn==19.9.0
      - itsdangerous==1.1.0
      - Jinja2==2.11.1
      - jmespath==0.9.4
      - MarkupSafe==1.1.1
      - prettytable==0.7.2
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycparser==2.19
      - pyOpenSSL==19.0.0
      - python-dateutil==2.8.1
      - python-jose==3.1.0
      - python-ldap==3.2.0
      - pytz==2019.1
      - PyYAML==5.2
      - requests==2.6.0
      - requests-aws4auth==0.9
      - rsa==3.4.2
      - s3transfer==0.2.1
      - six==1.14.0
      - troposphere==2.5.3
      - urllib3==1.25.8
      - Werkzeug==1.0.0
      - WTForms==2.2.1
    executable: "/apps/soca/{{ SOCA_CLUSTER_ID }}/python/latest/bin/pip3"